FROM ghcr.io/ihsenalaya/cc-contract-torch@sha256:d529bf986f595c1d0159786e6cdcd1fec3d65d2281689b45b6040244df7b8ccf
ARG CC_COMMIT
LABEL org.opencontainers.image.source="https://github.com/ihsenalaya/cc-contract" org.opencontainers.image.revision="$CC_COMMIT"
COPY --chown=10001:10001 src/ /app/src/
USER 10001:10001
ENTRYPOINT ["python", "-m", "cc_contract.hdsc_ai"]
